### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by MasterFee** [MikeLydeamore/ExNihiloAdscensio#98]
Game crashes on startup when using mod along with ZeroCore, Extreme Reactors & Actually Additions. After the latest updates of ZeroCore and Extreme Reactors Ex Nihilo Adscensio on startup. Reported the crash to the developers of Actually Additions (which caused the crash if you can trust the crash report) and ZeroCore. Both said that it's not caused by their mod. Actually Additions developer Ellpeck:

> It is caused by a broken furnace recipe in the furnace recipe registry that either doesn't have an input or an output item. This isn't supposed to happen, which is why I didn't check for it when writing the booklet code that crashes here, meaning this isn't actually an issue caused by me regardless because it's an invalid game state, really.

(Game crashes because the furnace recipe cannot be shown inside the Actually Additions Manual)

Link to the other issue post (source if the quote as well as prior crash report):
https://github.com/Ellpeck/ActuallyAdditions/issues/646
Initial crash report:
http://pastebin.com/5AkxRmJK

**Comment by MikeLydeamore** [comment]
I think I have fixed this in 99abb53bbd82859b3cf55dea571b1ebe684f34fb but was unable to reproduce so cannot be sure. Please reopen if it persists in the future.

**Comment by MasterFee** [comment]
I am afraid to tell you but the update did not fix it, for me at least. Crash only seems to happen in my custom mod pack. Sky Factory 3 is similar to my mod pack only difference being that I use updated version of the mods. Problem is solved by either disabling Ex Nihilo Adscensio or downgrading ZeroCore and Extreme Reactors.
If you want a mod list of the mods I'm currently using let me know.
